### ISSUE TITLE
FEATURE: Fix footer on search results page

### ISSUE THREAD

**Issue by tinaadams25** [gaskij/rpicampusmap#126]
When scrolling down through the results on the browse page, the red footer bar with the link to our GitHub does not stay at the bottom of the page.

**Comment by gaskij** [comment]
What branch does this occur on?

**Comment by Unachieved** [comment]
dev

**Comment by gaskij** [comment]
Okay, thank you for pointing this out but I think there's still some confusion here. `dev` should not be in active development right now. New features shouldn't be added to `dev`, and there are probably plenty of bugs right now because its still being fixed. You guys don't have to worry about even looking at `dev`. If I were you, I'd run far away from it lol. Any new tickets opened and new features made should all be based on `master` and `master` only.
